### ISSUE TITLE
vue^2.6.14 可以使用吗

### ISSUE THREAD

**Issue by Sansuihe** [keno-lee/vue-virt-list#20]
我的项目上vue^2.6.14版本 现在使用的时候提示
permission.js:35 TypeError: (0 , vue_demi__WEBPACK_IMPORTED_MODULE_1__.defineComponent) is not a function
    at eval (index.js:46:94)
    at ./node_modules/vue-virt-list/lib/index.js (true~node_modules_vue-.js:2:109286)
    at __webpack_require__ (app~src_m.js:2:481256)
    at eval (index.js??clonedRule…cript&lang=js:32:72)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/chat/content/index.vue?vue&type=script&lang=js (src_views_chat_conte…index_vue.js:2:8176)
    at __webpack_require__ (app~src_m.js:2:481256)
    at eval (index.vue?vue&type=script&lang=js:2:218)
    at ./src/views/chat/content/index.vue?vue&type=script&lang=js (src_views_chat_conte…index_vue.js:2:4623)
    at __webpack_require__ (app~src_m.js:2:481256)
    at eval (index.vue:3:92)

**Comment by keno-lee** [comment]
可以使用，但是要安装 @vue/composition-api
